name: Go + Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build Go project
      run: go build -v ./cmd/bot

    - name: Run tests
      run: go test ./...

    - name: Build Docker image
      run: docker build -t botqr .
